#!/bin/bash

if [ -t 1 ]; then
  R=$(tput setaf 1)
  G=$(tput setaf 2)
  Y=$(tput setaf 3)
  N=$(tput sgr0)
fi

args=""
files=""

home_dir="~"

INPLACE=0
FORMAT=0

for OPT in "$@"
do
  case "$1" in
    --format)
      FORMAT=1
      args="${args} $1"
      ;;
    --*)
      for w in $(echo $1 | tr "=" " ")
      do
        replaced=${w//$home_dir/$HOME}
        args="${args} ${replaced}"
      done
      ;;
    -i)
      INPLACE=1
      ;;
    -*)
      for w in $(echo $1 | tr "=" " ")
      do
        args="${args} $w"
      done
      ;;
    *)
      files="${files} $1"
      ;;
  esac
  shift
done

retval=0

for FILE in ${files}; do
  tmpfile=$(mktemp)
  if ! xmllint ${args} $FILE > $tmpfile; then
      echo "XML check for $FILE: ${R}cannot parse or mismatch schema${N}"
      retval=1
  else
    if [ ${FORMAT} -eq 1 ]; then
      if ! diff $tmpfile $FILE; then
        if [ $INPLACE -eq 0 ]; then
          echo "XML check for $FILE: ${R}failed${N}"
          retval=2
        else
          cp $tmpfile $FILE
          echo "XML check for $FILE: ${Y}reformatted${N}"
        fi
      else
        echo "XML check for $FILE: ${G}OK${N}"
      fi
    fi
  fi
  rm -f $tmpfile
done

exit $retval
